function vec = quatrotate_(q,vec)
      rows = size(vec,1);
      qV = [zeros(rows,1),vec];
      q_inv = q;
      q_inv(2:4) = -q_inv(2:4);
      q = repmat(q,rows,1);
      q_inv = repmat(q_inv,rows,1);
      temp_ = quaternion_multiply(quaternion_multiply(q,qV),q_inv);
      vec = temp_(:,2:4);